project:
  type: website

website:
  title: "Taimur Khan"
  navbar:
    left:
      - href: index.qmd
        text: About
      - projects.qmd
      - href: courses.qmd
        text: Teaching
    right:
      - href: "mailto:thisistaimur@icloud.com"
        text: ✉️

format:
  html:
    theme: 
      light: morph
    css: styles.css
    toc: true



