project:
  type: website
  resources: 
    - images/
    - CNAME

website:
  title: "Taimur Khan"
  site-url: "https://thisistaimur.github.io"
  description: "Deep Learning | Remote Sensing | HPC | Computer Vision"
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Teaching
      - href: publications.qmd
        text: Research
      - href: https://thisistaimur.me/lab
        text: Lab  
    right:
      - href: "mailto:thisistaimur@icloud.com"
        text: Email

  body-footer: |
    © 2022 - 2026 Taimur Khan - All Rights Reserved.

format:
  html:
    theme:
      light: morph
    css: styles.css
    include-in-header: includes/seo.html
    canonical-url: true
    toc: true
