project:
  type: website

website:
  title: "Taimur Khan"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications
    right:
      - href: "mailto:thisistaimur@icloud.com"
        text: 📮

format:
  html:
    theme: 
      light: morph
    css: styles.css
    toc: true



