project:
  type: website

resources:
  - CNAME
website:
  title: "Taimur Khan"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications
    right:
      - href: "mailto:thisistaimur@icloud.com"
        text: 📮

  body-footer: |
    © Taimur Khan.

format:
  html:
    theme:
      light: morph
      dark: darkly
    css: styles.css
    toc: true
