project:
  type: website
  resources: 
    - images/
    - CNAME

website:
  title: "Taimur Khan"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications
      - href: https://thisistaimur.me/lab
        text: Lab  
    right:
      - href: "mailto:thisistaimur@icloud.com"
        text: 📮

  body-footer: |
    © 2022 - 2024 Taimur Khan - All Rights Reserved.

format:
  html:
    theme:
      light: morph
    css: styles.css
    toc: true
