# References

- Trantas, A., Mensio, M., Stasinos, S., Gribincea, S., Khan, T., Podareanu, D., & van der Veen, A. (2025). BioAnalyst: A Foundation Model for Biodiversity. arXiv preprint arXiv:2507.09080. Pre-print DOI: [https://doi.org/10.48550/arXiv.2507.09080](https://doi.org/10.48550/arXiv.2507.09080)
- Khan, T., Krebs, J., Gupta, S. K., Renkel, J., Arnold, C., Nölke, N., … Grimm, V. (2025). Validation Challenges in Large‑Scale Tree Crown Segmentations from Remote Sensing Imagery Using Deep Learning: A Case Study in Germany. In Proceedings of The 29th
International Conference on Theory and Practice of Digital Libraries,
TPDL 2025 Workshops, Tampere, Finland, September 23-26, 2025, Lecture Notes in Computer Science (LNCS) (Vol. XXX, pp. xxx–xxx). Springer. DOI:
- Khan, T., Arnold, C., & Grover, H. (2025). DeepTrees: Tree crown segmentation and analysis in remote sensing imagery with PyTorch. [In-review](https://github.com/openjournals/joss-reviews/issues/8056). Pre-print DOI: http://dx.doi.org/10.13140/RG.2.2.32837.36329
- Taubert, F., Banitz, T., Brewster, C., Davison, A. M., Groeneveld, J., Khan, T. H., de Koning, K., Kusch, E., Rolph, S., Grimm, V., & Nikolova, N. (2025). The process and challenges of developing Digital Twins for ecology. In-review.
- **Khan, T.**, de Koning, K., Endresen, D., Chala, D., Kusch, E.  TwinEco: A Unified Framework for Dynamic Data-Driven Digital Twins in Ecology. In-Review. Pre-print DOI: [https://doi.org/10.1101/2024.07.23.604592](https://doi.org/10.1101/2024.07.23.604592)
- Taubert, F., Rossi, T., Wohner, C., Venier, S., Martinovič, T., **Khan, T.**, ... & Banitz, T. (2024). Prototype Biodiversity Digital Twin: grassland biodiversity dynamics. Research Ideas and Outcomes, 10, e124168. DOI: [https://doi.org/10.3897/rio.10.e124168](https://doi.org/10.3897/rio.10.e124168)
- **Khan, T.**, El-Gabbas, A., Golivets, M., Souza, A., Gordillo, J., Kierans, D., & Kühn, I. (2024). Prototype Biodiversity Digital Twin: Invasive Alien Species. Research Ideas and Outcomes, 10, e124579. DOI: [https://doi.org/10.3897/rio.10.e124579](https://doi.org/10.3897/rio.10.e124579)
- **Khan, T.** (2023). Designing Data Drive Digital Twin Systems. Workshop 9: European Conference on Ecological Modeling 2023. DOI: [https://doi.org/10.5281/zenodo.8313904](https://doi.org/10.5281/zenodo.8313904)
- **Khan, T.**, Banitz, T., Golivets, M., Grimm, V., Groeneveld, J., Kühn, I., Taubert, F. (2022). Prototyping a Biodiversity Digital Twin. Helmholtz-UFZ Science Days 2022. DOI: [https://doi.org/10.5281/zenodo.8079131](https://doi.org/10.5281/zenodo.8079131)
- Morche, D., Baewert, H., Schuchardt, A., Faust, M., Weber, M., & **Khan, T.** (2019). Fluvial sediment transport in the proglacial Fagge river, Kaunertal, Austria. Geomorphology of Proglacial Systems (pp. 219-229). Springer, Cham. DOI: [https://doi.org/10.1007/978-3-319-94184-4_13](https://doi.org/10.1007/978-3-319-94184-4_13)
- **Khan, T.** (2017). DC Resistivity: Estimating pore moisture distribution and mapping permafrost content in Kaunertal, Austria. Department of Geosciences. Skidmore College.